services:
  payment:
    container_name: payment-service
    build: ./payment
    volumes:
      - ./payment:/app:ro
      - ./data:/data

  search:
    container_name: search-service
    build: ./search
    volumes:
      - ./search:/app:ro
      - ./data:/data

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - payment
      - search
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml:ro
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/config.yml:ro
    command:
      - -config.file=/etc/promtail/config.yml
      - --server.enable-runtime-reload

  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - SLACK_WEBHOOK
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  cadvisor:
    container_name: cAdvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    environment:
      - --detach=true
      - --privileged
      - --device=/dev/kmsg

  k6:
    container_name: k6
    image: grafana/k6
    depends_on:
      - nginx
    volumes:
      - ./grafana/scripts:/scripts:ro
    environment:
      - K6_OUT=experimental-prometheus-rw
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - FAULT_RATE=0.02
      - EXTRA_LATENCY_MS=200
    command: run -o experimental-prometheus-rw /scripts/script.js
