services:
    payment:
        container_name: payment-service
        build: ./payment
        volumes:
            - ./payment:/app:ro
            - ./data:/data

    search:
        container_name: search-service
        build: ./search
        volumes:
            - ./search:/app:ro
            - ./data:/data

    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 8000:80
        depends_on:
            - payment
            - search
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
