global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: payment-service
    static_configs:
      - targets: ["payment:8000"]

  - job_name: search-service
    static_configs:
      - targets: ["search:8001"]
