groups:
  - name: tenant-sli-rules
    rules:
      - record: sli:availability
        expr: sum(rate(tenant_requests_total{path!="/metrics",status!~"[4|5].."}[30d])) / sum(rate(tenant_requests_total{path!="/metrics"}[30d])) * 100

      - record: sli:availability_per_service
        expr: sum by (job) (rate(tenant_requests_total{path!="/metrics",status!~"[4|5].."}[30d])) / sum by (job) (rate(tenant_requests_total{path!="/metrics"}[30d])) * 100

      - record: sli:latency_ms:p95
        expr: histogram_quantile(0.95, sum by(le) (rate(tenant_request_latency_seconds_bucket{status!~"[4|5]..",path!="/metrics"}[30d]))) * 1000

      - record: sli:latency_ms:p99
        expr: histogram_quantile(0.99, sum by(le) (rate(tenant_request_latency_seconds_bucket{status!~"[4|5]..",path!="/metrics"}[30d]))) * 1000

      - record: sli:error_rate
        expr: sum(rate(tenant_requests_total{path!="/metrics",status=~"[4|5].."}[30d])) / sum(rate(tenant_requests_total{path!="/metrics"}[30d])) * 100

      - record: sli:error_rate_per_service
        expr: sum by (job) (rate(tenant_requests_total{path!="/metrics",status=~"[4|5].."}[30d])) / sum by (job) (rate(tenant_requests_total{path!="/metrics"}[30d])) * 100

  - name: tenant-slo-rules
    rules:
      - alert: slo:availability_violation
        expr: sli:availability < 99.9
        annotations:
          summary: "Availability SLO violation"
          description: "The availability dropped below 99.9%"

      - alert: slo:p95_latency_violation
        expr: sli:latency_ms:p95 > 300
        annotations:
          summary: "P95 Latency SLO violation"
          description: "The 95th percentile latency is above 300ms"

      - alert: slo:p99_latency_violation
        expr: sli:latency_ms:p99 > 800
        annotations:
          summary: "P99 Latency SLO violation"
          description: "The 99th percentile latency is above 800ms"

      - alert: slo:error_budget_burn_2x:1h
        expr: sli:error_rate / 0.1 > 2
        for: 1h
        labels:
          severity: page
        annotations:
          summary: "2x Error Budget Burn"
          description: "Tenant is burning error budget >2x over the last 1h."

      - alert: slo:error_budget_burn_4x:1m
        expr: sli:error_rate / 0.1 > 4
        for: 1m
        labels:
          severity: page
          action: "freeze"
        annotations:
          summary: "4x Error Budget Burn"
          description: "Tenant is burning error budget >4x over the last 15 minutes"
