groups:
  - name: tenant-sli-rules
    rules:
      - record: sli:availability
        expr: sum(rate(tenant_requests_total{path!="/metrics",status!~"[4|5].."}[5m])) / sum(rate(tenant_requests_total{path!="/metrics"}[5m])) * 100

      - record: sli:availability_per_service
        expr: sum by (job) (rate(tenant_requests_total{path!="/metrics",status!~"[4|5].."}[5m])) / sum by (job) (rate(tenant_requests_total{path!="/metrics"}[5m])) * 100

      - record: sli:latency_ms:p95
        expr: histogram_quantile(0.95, sum by(le) (rate(tenant_request_latency_seconds_bucket{status!~"[4|5]..",path!="/metrics"}[5m]))) * 1000

      - record: sli:latency_ms:p99
        expr: histogram_quantile(0.99, sum by(le) (rate(tenant_request_latency_seconds_bucket{status!~"[4|5]..",path!="/metrics"}[5m]))) * 1000

      - record: sli:error_rate
        expr: sum(rate(tenant_requests_total{path!="/metrics",status=~"[4|5].."}[5m])) / sum(rate(tenant_requests_total{path!="/metrics"}[5m])) * 100

      - record: sli:error_rate_per_service
        expr: sum by (job) (rate(tenant_requests_total{path!="/metrics",status=~"[4|5].."}[5m])) / sum by (job) (rate(tenant_requests_total{path!="/metrics"}[5m])) * 100

  - name: tenant-slo-rules
    rules:
      - alert: slo:availability_violation
        expr: sli:availability < 99.9
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Availability SLO violation"
          description: "The availability dropped below 99.9% for the last 5 minutes"

      - alert: slo:latency_p95_violation
        expr: sli:latency_ms:p95 > 500
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Latency SLO violation"
          description: "The 95th percentile latency is above 500ms for the last 5 minutes"

      - alert: slo:latency_p99_violation
        expr: sli:latency_ms:p99 > 1000
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Latency SLO violation"
          description: "The 99th percentile latency is above 1000ms for the last 5 minutes"

      - alert: slo:error_rate_violation
        expr: sli:error_rate > 5
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Error Rate SLO violation"
          description: "The error rate is above 5% for the last 5 minutes"
