{
 "title": "Multi-tenant-SRE-sandbox-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payment service log panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"payment\"}"
      }
     ]
    },
    {
     "title": "Payment service error logs panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"payment\", status=~\"[4|5]..\"}"
      }
     ]
    },
    {
     "title": "Search service log panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"search\"}"
      }
     ]
    },
    {
     "title": "Search service error logs panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"search\", status=~\"[4|5]..\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(\n    rate(\n        tenant_requests_total{path!=\"/metrics\"}[$__rate_interval]\n    )\n    or on() vector(0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS per service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (job) (\n    rate(tenant_requests_total{path!=\"/metrics\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS per path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(tenant_requests_total{path!~\"/metrics\"}[$__rate_interval])) by (path)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPS per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(tenant_requests_total{path!~\"/metrics\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "LPR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "LPR",
     "type": "timeseries",
     "description": "Latency per request in ms",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 787 },
     "targets": [
      {
       "expr": "sum(\n  rate(\n    tenant_request_latency_seconds_sum{path!=\"/metrics\"}[$__rate_interval]\n  )\n)\n* 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LPR per path",
     "type": "timeseries",
     "description": "Latency per request per path in ms",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 787 },
     "targets": [
      {
       "expr": "sum by (path) (\n  rate(\n    tenant_request_latency_seconds_sum{path!=\"/metrics\"}[$__rate_interval]\n  )\n)\n* 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LPR per tenant",
     "type": "timeseries",
     "description": "Latency per request per tenant in ms",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 899 },
     "targets": [
      {
       "expr": "sum by (tenant) (\n  rate(\n    tenant_request_latency_seconds_sum{path!=\"/metrics\"}[$__rate_interval]\n  )\n) * 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 788 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(tenant_request_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "p95 latency per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 788 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, tenant) (\n    rate(tenant_request_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "p99 latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 828 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(tenant_request_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "p99 latency per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 828 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le, tenant) (\n    rate(tenant_request_latency_seconds_bucket{path!=\"/metrics\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(tenant_requests_total{path!=\"/metrics\",status=~\"[4|5]..\"}[$__rate_interval]))\n/\nsum(rate(tenant_requests_total{path!=\"/metrics\"}[$__rate_interval]))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate per service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by (job) (rate(tenant_requests_total{path!=\"/metrics\",status=~\"[4|5]..\"}[$__rate_interval]))\n/\nsum by (job) (rate(tenant_requests_total{path!=\"/metrics\"}[$__rate_interval]))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate per path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (path) (rate(tenant_requests_total{path!=\"/metrics\",status=~\"[4|5]..\"}[$__rate_interval]))\n/\nsum by (path) (rate(tenant_requests_total{path!=\"/metrics\"}[$__rate_interval]))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error rate per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (tenant) (rate(tenant_requests_total{path!=\"/metrics\",status=~\"[4|5]..\"}[$__rate_interval]))\n/\nsum by (tenant) (rate(tenant_requests_total{path!=\"/metrics\"}[$__rate_interval]))\n* 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}